const GET_ALL_CONTACTS_INIT = 'GET_ALL_CONTACTS_INIT'
const GET_ALL_CONTACTS_SUCCESS = 'GET_ALL_CONTACTS_SUCCESS'
const GET_ALL_CONTACTS_FAIL = 'GET_ALL_CONTACTS_FAIL'

export {
	GET_ALL_CONTACTS_INIT,
	GET_ALL_CONTACTS_SUCCESS,
	GET_ALL_CONTACTS_FAIL
}
